# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               The Software Engineering Life Cycle
#tagline:             'A Jekyll theme'
# description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://www.thesoftwareengineeringlifecycle.com
baseurl:             'http://www.thesoftwareengineeringlifecycle.com/TheSoftwareEngineeringLifeCycle'
paginate:            5

# About/contact
author:
  name:              Anuruddha Pathiranage
  url:               https://twitter.com/AijPathirana
  email:             aijpathirana@gmail.com

# Custom vars
version:             1.0.0
